using SelfOrganizer.Core.Models;

namespace SelfOrganizer.Core.Interfaces;

public interface ISchedulingService
{
    Task<IEnumerable<TimeBlock>> GenerateTimeBlocksAsync(DateOnly date);
    Task<IEnumerable<TimeBlock>> GetTimeBlocksForDateAsync(DateOnly date);
    Task<TimeBlock> CreateTimeBlockAsync(TimeBlock timeBlock);
    Task<TimeBlock> UpdateTimeBlockAsync(TimeBlock timeBlock);
    Task DeleteTimeBlockAsync(Guid id);
    Task<IEnumerable<TimeBlock>> AutoScheduleTasksAsync(DateOnly date, IEnumerable<TodoTask> tasks);
    Task ClearAutoGeneratedBlocksAsync(DateOnly date);
}
