using SelfOrganizer.Core.Models;

namespace SelfOrganizer.Core.Interfaces;

public interface ISchedulingService
{
    Task<IEnumerable<TimeBlock>> GenerateTimeBlocksAsync(DateOnly date);
    Task<IEnumerable<TimeBlock>> GetTimeBlocksForDateAsync(DateOnly date);
    Task<TimeBlock> CreateTimeBlockAsync(TimeBlock timeBlock);
    Task<TimeBlock> UpdateTimeBlockAsync(TimeBlock timeBlock);
    Task DeleteTimeBlockAsync(Guid id);
    Task<IEnumerable<TimeBlock>> AutoScheduleTasksAsync(DateOnly date, IEnumerable<TodoTask> tasks);
    Task ClearAutoGeneratedBlocksAsync(DateOnly date);

    // Goal-aware scheduling methods
    Task<IEnumerable<GoalProgressReport>> GetGoalProgressReportsAsync();
    Task<IEnumerable<TodoTask>> GetGoalSubtasksForSchedulingAsync(Guid goalId);
    Task<IEnumerable<TimeBlock>> AutoScheduleWithGoalAwarenessAsync(DateOnly date, IEnumerable<TodoTask> tasks, IEnumerable<Goal> goals);
}
