namespace SelfOrganizer.Core.Models;

/// <summary>
/// Time block - scheduled work period
/// </summary>
public class TimeBlock : BaseEntity
{
    public DateTime StartTime { get; set; }
    public DateTime EndTime { get; set; }
    public TimeBlockType Type { get; set; }
    public Guid? LinkedEventId { get; set; }
    public List<Guid> AssignedTaskIds { get; set; } = new();
    public string? Notes { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? Category { get; set; }

    public int DurationMinutes => (int)(EndTime - StartTime).TotalMinutes;
}
