// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfOrganizer.Server.Data;

#nullable disable

namespace SelfOrganizer.Server.Migrations
{
    [DbContext(typeof(SelfOrganizerDbContext))]
    partial class SelfOrganizerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SelfOrganizer.Core.Models.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attendees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AutoCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecompressTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoLinked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLinkAnalysisAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("LinkedGoalIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LinkedIdeaIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LinkedProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkedTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OverrideCategory")
                        .HasColumnType("int");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresFollowUp")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresPrep")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.CaptureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CleanedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("ExtractedTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedIntoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProcessedIntoType")
                        .HasColumnType("int");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Captures");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.CareerPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedGoalIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedHabitIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedProjectIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedSkillIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Milestones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CareerPlans");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.CategoryDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDecompressMinutes")
                        .HasColumnType("int");

                    b.Property<int>("DefaultEnergyRequired")
                        .HasColumnType("int");

                    b.Property<int>("DefaultPrepMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<string>("MatchTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TypicallyRequiresFollowUp")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.Context", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contexts");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.DailySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapturesProcessed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayReflection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeepWorkMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("EveningAccomplishment")
                        .HasColumnType("int");

                    b.Property<bool>("EveningCheckoutCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EveningCheckoutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<int>("MeetingMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MorningCheckinCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MorningCheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MorningEnergy")
                        .HasColumnType("int");

                    b.Property<string>("MorningGratitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MorningIntention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MorningMood")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("TasksCompleted")
                        .HasColumnType("int");

                    b.Property<int>("TasksCreated")
                        .HasColumnType("int");

                    b.Property<string>("TopPriorityTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMinutesWorked")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailySnapshots");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.EntityLinkRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ApplyToAttendees")
                        .HasColumnType("bit");

                    b.Property<bool>("ApplyToDescription")
                        .HasColumnType("bit");

                    b.Property<bool>("ApplyToTags")
                        .HasColumnType("bit");

                    b.Property<bool>("ApplyToTitle")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<double>("MinConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetEntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EntityLinkRules");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.FocusSessionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualElapsedSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnergyLevel")
                        .HasColumnType("int");

                    b.Property<int>("ExtensionCount")
                        .HasColumnType("int");

                    b.Property<int>("FocusRating")
                        .HasColumnType("int");

                    b.Property<string>("Intention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalEstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TaskCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalExtensionMinutes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("WasDistracted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FocusSessionLogs");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiGeneratedPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BalanceDimensionIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BalanceImpact")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionChallenges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionLessonsLearned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionReflection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesiredOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedHabitIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedProjectIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedSkillIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NextActionTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obstacles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryBalanceDimensionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SuccessCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiRationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedGoalIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedSkillIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("PreferredTime")
                        .HasColumnType("time");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetCount")
                        .HasColumnType("int");

                    b.Property<string>("TrackedDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.HabitLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HabitLogs");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ConvertedToTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasActionPotential")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LinkedGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkedProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionChallenges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionLessonsLearned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionReflection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesiredOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedSkillIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("NextActionTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.ReferenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("LinkedProjectIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("LinkedTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiRationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentProficiency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedGoalIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedHabitIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedProjectIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetProficiency")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.TaskReminderSnooze", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SnoozedUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaskReminderSnoozes");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.TimeBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LinkedEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TimeBlocks");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.TodoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualMinutes")
                        .HasColumnType("int");

                    b.Property<string>("BlockedByTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contexts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DetectedCategory")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnergyLevel")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("GoalIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIconAutoDetected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRecurrenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedMeetingIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedTaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RecurrenceIntervalDays")
                        .HasColumnType("int");

                    b.Property<int?>("RecurrencePattern")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresDeepWork")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkillIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubtaskIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("WaitingForContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WaitingForNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WaitingForSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhoFor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accessibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AfternoonEnergyPeak")
                        .HasColumnType("int");

                    b.Property<int>("AppMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AppModeSetAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AutoDarkMode")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoExpandNextActions")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoScheduleEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoStartBreakTimer")
                        .HasColumnType("bit");

                    b.Property<bool>("BalanceAiShowInsights")
                        .HasColumnType("bit");

                    b.Property<bool>("BalanceAiSuggestGoals")
                        .HasColumnType("bit");

                    b.Property<bool>("BalanceAiSuggestTasks")
                        .HasColumnType("bit");

                    b.Property<int>("BalanceAiThreshold")
                        .HasColumnType("int");

                    b.Property<string>("BalanceRatingsByMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlockedTaskPenalty")
                        .HasColumnType("int");

                    b.Property<int>("BreakReminderMinutes")
                        .HasColumnType("int");

                    b.Property<int>("BufferBetweenMeetingsMinutes")
                        .HasColumnType("int");

                    b.Property<int>("CelebrationIntensity")
                        .HasColumnType("int");

                    b.Property<string>("ContextDimensionMappings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContextGroupingWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyReviewReminderHour")
                        .HasColumnType("int");

                    b.Property<int>("DailyTaskGoal")
                        .HasColumnType("int");

                    b.Property<int>("DarkModEndHour")
                        .HasColumnType("int");

                    b.Property<int>("DarkModeStartHour")
                        .HasColumnType("int");

                    b.Property<int>("DeepWorkMinimumMinutes")
                        .HasColumnType("int");

                    b.Property<int>("DeepWorkPreferenceWeight")
                        .HasColumnType("int");

                    b.Property<int>("DefaultBreakMinutes")
                        .HasColumnType("int");

                    b.Property<int>("DefaultTaskDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("DueDateUrgencyWeight")
                        .HasColumnType("int");

                    b.Property<bool>("EnableAmbientTimeDisplay")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableBlockerPrompts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableBodyDoubling")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCelebrationEffects")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCommitmentMode")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableContextSwitchWarnings")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDailyGoalSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableEveningWindDown")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableFocusSounds")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableFocusStreaks")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableFocusTimer")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableGentleReminders")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableHyperfocusAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableMicroRewards")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableMinimalMode")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableMorningPlanningPrompt")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePickForMe")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableProgressVisualization")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableQuickCaptureMode")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableTaskChunking")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableTaskTransitions")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableTimeBlindnessHelpers")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableWeeklySummary")
                        .HasColumnType("bit");

                    b.Property<string>("EnabledBalanceDimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnergyMatchingWeight")
                        .HasColumnType("int");

                    b.Property<int>("EveningWindDownHour")
                        .HasColumnType("int");

                    b.Property<int>("FocusTimerMinutes")
                        .HasColumnType("int");

                    b.Property<string>("GoogleCalendarAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleCalendarEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GoogleCalendarLastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleCalendarRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleCalendarSelectedCalendarIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoogleCalendarSyncFutureDays")
                        .HasColumnType("int");

                    b.Property<int>("GoogleCalendarSyncPastDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GoogleCalendarTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HideDueDatesOnCards")
                        .HasColumnType("bit");

                    b.Property<bool>("HideTaskCounts")
                        .HasColumnType("bit");

                    b.Property<int>("HyperfocusAlertMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LifeAreaAssessmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LifeAreaRatings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LongBreakMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxConsecutiveMeetingMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxTaskChunkMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxVisibleTasks")
                        .HasColumnType("int");

                    b.Property<int>("MinimumUsableBlockMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MorningEnergyPeak")
                        .HasColumnType("int");

                    b.Property<int>("MorningPlanningHour")
                        .HasColumnType("int");

                    b.Property<bool>("MuteAllSounds")
                        .HasColumnType("bit");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("OneTaskAtATimeMode")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OutlookCalendarLastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutlookCalendarSelectedIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutlookCalendarSyncFutureDays")
                        .HasColumnType("int");

                    b.Property<int>("OutlookCalendarSyncPastDays")
                        .HasColumnType("int");

                    b.Property<bool>("PauseTimerOnWindowBlur")
                        .HasColumnType("bit");

                    b.Property<bool>("PlayTimerCompletionSound")
                        .HasColumnType("bit");

                    b.Property<int?>("PreferredCalendarProvider")
                        .HasColumnType("int");

                    b.Property<int>("PreferredFocusSound")
                        .HasColumnType("int");

                    b.Property<bool>("RequireAbandonReason")
                        .HasColumnType("bit");

                    b.Property<bool>("SampleDataSeeded")
                        .HasColumnType("bit");

                    b.Property<int>("SessionsBeforeLongBreak")
                        .HasColumnType("int");

                    b.Property<bool>("ShowDailyProgressBar")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowElapsedTime")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEncouragingMessages")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEstimatedCompletion")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPostSessionReflection")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSampleData")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSessionIntentionPrompt")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowTimeRemainingInBlock")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowTimeSinceLastBreak")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowTimerNotification")
                        .HasColumnType("bit");

                    b.Property<int>("SimilarWorkGroupingWeight")
                        .HasColumnType("int");

                    b.Property<bool>("SimplifiedTaskView")
                        .HasColumnType("bit");

                    b.Property<int>("SoundVolume")
                        .HasColumnType("int");

                    b.Property<int>("StakeholderGroupingWeight")
                        .HasColumnType("int");

                    b.Property<int>("StaleTakPromptDays")
                        .HasColumnType("int");

                    b.Property<bool>("SuggestTaskBreakdown")
                        .HasColumnType("bit");

                    b.Property<int>("TagSimilarityWeight")
                        .HasColumnType("int");

                    b.Property<int>("TaskBreakdownThresholdMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TaskStartGracePeriod")
                        .HasColumnType("int");

                    b.Property<int>("TimeAwarenessIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("TrackDistractions")
                        .HasColumnType("bit");

                    b.Property<int>("TransitionBufferMinutes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WeeklyReviewDay")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("WorkDayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkDayStart")
                        .HasColumnType("time");

                    b.Property<string>("WorkDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("SelfOrganizer.Core.Models.WeeklySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AverageEnergyLevel")
                        .HasColumnType("int");

                    b.Property<int?>("AverageMoodLevel")
                        .HasColumnType("int");

                    b.Property<string>("BiggestChallenge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BiggestWin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CalendarReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysWithMorningCheckin")
                        .HasColumnType("int");

                    b.Property<string>("GratitudeReflection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HabitsCompletedCount")
                        .HasColumnType("int");

                    b.Property<bool>("InboxCleared")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("bit");

                    b.Property<string>("LessonsLearned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextWeekFocus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextWeekPriorities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherWins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductivityRating")
                        .HasColumnType("int");

                    b.Property<bool>("ProjectsReviewed")
                        .HasColumnType("bit");

                    b.Property<bool>("ReviewCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("SomedayMaybeReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("TotalDeepWorkMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TotalMeetingMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TotalMinutesWorked")
                        .HasColumnType("int");

                    b.Property<int>("TotalTasksCompleted")
                        .HasColumnType("int");

                    b.Property<int>("TotalTasksCreated")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("WaitingForReviewed")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.Property<int?>("WorkLifeBalanceRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
